### ISSUE TITLE
Issues with groovy console 3.0.1

### ISSUE THREAD

**Issue by mantho29** [Citytechinc/cq-groovy-console#26]
Hi Mark,

I am using groovy console 3.0.1 on cq 5.5 instance:

https://github.com/Citytechinc/cq-groovy-console

I am getting the following issues after install with components not registering.

I am using CURL to deploy the packages.

Any additional instructions to do after during the normal install.

Below are the issues:

/system/console/components

com.citytechinc.cqlibrary.groovyconsole.servlets.ScriptSavingServlet registered

The above component is in "registered" state than "active".

Failed creating the component instance; see log for reason
08.08.2014 00:55:05.950 *ERROR* [OsgiInstallerImpl] org.apache.sling.servlets.resolver.internal.SlingServletResolver bindServlet: Servlet service not available from reference [javax.servlet.Servlet]

The activate method has thrown an exception (java.lang.VerifyError: (class: org/codehaus/groovy/runtime/ArrayUtil, method: createArray signature: ()[Ljava/lang/Object;) Illegal type in constant pool) java.lang.VerifyError: (class: org/codehaus/groovy/runtime/ArrayUtil, method: createArray signature: ()[Ljava/lang/Object;) Illegal type in constant pool

Please let me know if you have seen these issues before and anyways of resolving it.

Thanks,

Mark

**Comment by ItGumby** [comment]
Attempting to load into CQ5.6.1 instance, and it fails for me also:

## Verify step
http://localhost:4502/etc/groovyconsole.html => 
```log
Full Exception:
org.apache.sling.api.scripting.ScriptEvaluationException: org.apache.sling.scripting.jsp.jasper.JasperException: /apps/groovyconsole/components/console/head.jsp(1,1) The absolute uri: http://www.citytechinc.com/taglibs/groovyconsole cannot be resolved in either web.xml or the jar files deployed with this application
...
Caused by: org.apache.sling.scripting.jsp.jasper.JasperException: /apps/groovyconsole/components/console/head.jsp(1,1) The absolute uri: http://www.citytechinc.com/taglibs/groovyconsole cannot be resolved in either web.xml or the jar files deployed with this application
	at org.apache.sling.scripting.jsp.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:40)
```

## Felix Bundle Console shows:
http://localhost:4502/system/console/bundles =>
* "AEM Groovy Console" v7.0.1.SNAPSHOT status="Installed". **unresolved imports**
  * com.day.cq.commons.jcr, version=[5.7,6)
  * com.day.cq.mailer, version=[5.8,6)
  * com.day.cq.search, version=[1.1,2)
  * com.day.cq.wcm.api, version=[1.2,2)
  * com.day.cq.wcm.tags, version=[5.7,6)
  * org.apache.felix.scr, v=[1.8,2)
  * org.apache.sling.api, v=[2.3,3)
  * org.apache.sling.api.resource, v=[2.5,3)
  * org.apache.sling.jcr.api, v=[2.2,3)
  * org.slf4j, version=[1.7,2)
* "AEM Groovy Extension Bundle" v0.9.0 status="Installed" **unresolved imports**
  * com.day.cq.commons.jcr, version=[5.7,6)
  * com.day.cq.wcm.api, version=[1.2,2)
  * org.slf4j, version=[1.7,2)

## (filtered) error.log
```log
05.02.2015 16:23:21.539 *ERROR* [FelixDispatchQueue] org.apache.sling.scripting.core.impl.ScriptEngineManagerFactory Cannot register ScriptEngineFactory  java.lang.ClassNotFoundException:  not found by org.apache.commons.jexl [2396]
05.02.2015 16:23:21.693 *ERROR* [FelixDispatchQueue] org.apache.sling.scripting.core.impl.ScriptEngineManagerFactory Cannot register ScriptEngineFactory  java.lang.ClassNotFoundException:  not found by org.apache.commons.jexl [2396]
05.02.2015 16:23:22.238 *ERROR* [FelixDispatchQueue] aem-groovy-console FrameworkEvent ERROR (org.osgi.framework.BundleException: Unresolved constraint in bundle aem-groovy-console [3274]: Unable to resolve 3274.0: missing requirement [3274.0] osgi.wiring.package; (&(osgi.wiring.package=com.citytechinc.aem.groovy.extension.builders)(version>=0.9.0)(!(version>=1.0.0))) [caused by: Unable to resolve 3275.0: missing requirement [3275.0] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.commons.jcr)(version>=5.7.0)(!(version>=6.0.0)))]) org.osgi.framework.BundleException: Unresolved constraint in bundle aem-groovy-console [3274]: Unable to resolve 3274.0: missing requirement [3274.0] osgi.wiring.package; (&(osgi.wiring.package=com.citytechinc.aem.groovy.extension.builders)(version>=0.9.0)(!(version>=1.0.0))) [caused by: Unable to resolve 3275.0: missing requirement [3275.0] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.commons.jcr)(version>=5.7.0)(!(version>=6.0.0)))]
05.02.2015 16:23:22.238 *ERROR* [FelixDispatchQueue] aem-groovy-extension-bundle FrameworkEvent ERROR (org.osgi.framework.BundleException: Unresolved constraint in bundle aem-groovy-extension-bundle [3275]: Unable to resolve 3275.0: missing requirement [3275.0] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.commons.jcr)(version>=5.7.0)(!(version>=6.0.0)))) org.osgi.framework.BundleException: Unresolved constraint in bundle aem-groovy-extension-bundle [3275]: Unable to resolve 3275.0: missing requirement [3275.0] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.commons.jcr)(version>=5.7.0)(!(version>=6.0.0)))

05.02.2015 16:24:06.272 *ERROR* [0:0:0:0:0:0:0:1 [1423178646141] GET /etc/groovyconsole.html HTTP/1.1] com.day.cq.wcm.tags.IncludeTag Error while executing script head.jsp org.apache.sling.api.scripting.ScriptEvaluationException: org.apache.sling.scripting.jsp.jasper.JasperException: /apps/groovyconsole/components/console/head.jsp(1,1) The absolute uri: http://www.citytechinc.com/taglibs/groovyconsole cannot be resolved in either web.xml or the jar files deployed with this application
	at org.apache.jsp.apps.groovyconsole.components.console.html_jsp._jspService(html_jsp.java:153)
	at org.apache.jsp.libs.foundation.components.primary.cq.Page.Page_jsp._jspService(Page_jsp.java:106)
Caused by: org.apache.sling.scripting.jsp.jasper.JasperException: /apps/groovyconsole/components/console/head.jsp(1,1) The absolute uri: http://www.citytechinc.com/taglibs/groovyconsole cannot be resolved in either web.xml or the jar files deployed with this application
05.02.2015 16:24:06.273 *ERROR* [0:0:0:0:0:0:0:1 [1423178646141] GET /etc/groovyconsole.html HTTP/1.1] com.day.cq.wcm.core.impl.WCMDebugFilter Error during include of SlingRequestPathInfo: path='/etc/groovyconsole/jcr:content', selectorString='null', extension='html', suffix='null' org.apache.sling.api.scripting.ScriptEvaluationException: org.apache.sling.scripting.jsp.jasper.JasperException: /apps/groovyconsole/components/console/head.jsp(1,1) The absolute uri: http://www.citytechinc.com/taglibs/groovyconsole cannot be resolved in either web.xml or the jar files deployed with this application
	at org.apache.jsp.libs.foundation.components.primary.cq.Page.Page_jsp._jspService(Page_jsp.java:106)
Caused by: org.apache.sling.scripting.jsp.jasper.JasperException: /apps/groovyconsole/components/console/head.jsp(1,1) The absolute uri: http://www.citytechinc.com/taglibs/groovyconsole cannot be resolved in either web.xml or the jar files deployed with this application
	at org.apache.jsp.apps.groovyconsole.components.console.html_jsp._jspService(html_jsp.java:153)
05.02.2015 16:24:06.306 *ERROR* [0:0:0:0:0:0:0:1 [1423178646141] GET /etc/groovyconsole.html HTTP/1.1] com.day.cq.wcm.core.impl.WCMDebugFilter Exception: org.apache.sling.scripting.jsp.jasper.JasperException: /apps/groovyconsole/components/console/head.jsp(1,1) The absolute uri: http://www.citytechinc.com/taglibs/groovyconsole cannot be resolved in either web.xml or the jar files deployed with this application org.apache.sling.api.scripting.ScriptEvaluationException: org.apache.sling.scripting.jsp.jasper.JasperException: /apps/groovyconsole/components/console/head.jsp(1,1) The absolute uri: http://www.citytechinc.com/taglibs/groovyconsole cannot be resolved in either web.xml or the jar files deployed with this application
	at org.apache.jsp.libs.foundation.components.primary.cq.Page.Page_jsp._jspService(Page_jsp.java:106)
Caused by: org.apache.sling.scripting.jsp.jasper.JasperException: /apps/groovyconsole/components/console/head.jsp(1,1) The absolute uri: http://www.citytechinc.com/taglibs/groovyconsole cannot be resolved in either web.xml or the jar files deployed with this application
	at org.apache.jsp.apps.groovyconsole.components.console.html_jsp._jspService(html_jsp.java:153)
```

**Comment by ItGumby** [comment]
Confirmed that when I checkout out the latest tag for CQ5.6.1 (`git checkout 6.1.2`), it installed correctly.
Operator error.
