### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by cmrockwell** [Citytechinc/cq-groovy-console#39]
This looks super useful, but I can't get it installed. I've cloned the project, and am attempting to install cq-groove-console using maven 3.1.1 and java 7.0_51. I'm running AEM6 SP2 locally on port 4502. I've tried mvn install -Plocal from develop and master branches. Any suggestions would be muy apreciado

Tests in error: 
  DefaultAuditServiceSpec>ProsperSpec.setupSpec:79->ProsperSpec.getRepository:380 » NoClassDefFound
  DefaultAuditServiceSpec>ProsperSpec.cleanupSpec:94->ProsperSpec.removeAllNodes:111 » NullPointer
  DefaultExtensionServiceSpec>ProsperSpec.setupSpec:79->ProsperSpec.getRepository:380 » NoClassDefFound
  DefaultExtensionServiceSpec>ProsperSpec.cleanupSpec:94->ProsperSpec.removeAllNodes:111 » NullPointer
  DefaultGroovyConsoleServiceSpec>ProsperSpec.setupSpec:79->ProsperSpec.getRepository:380 » NoClassDefFound
  DefaultGroovyConsoleServiceSpec>ProsperSpec.cleanupSpec:94->ProsperSpec.removeAllNodes:111 » NullPointer

**Comment by steeleforge** [comment]
java 7 for aem & cq-groovy-console compilation?

I guess you can try to see if you can get it just going with -DskipTests=true

**Comment by cmrockwell** [comment]
OK Thanks. That works no prob.

**Comment by lykorian** [comment]
I tried to duplicate the build issue locally on OS X with identical Java and Maven versions, but the build (and tests) were successful.  Can you try running `mvn clean install` as well to see if that helps?

**Comment by cmrockwell** [comment]
Sure. Here's the result... Maybe I need some mvn repo in my settings.xml?

ldev-x-cmrockwe:cq-groovy-console cmrockwe$ mvn clean install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building AEM Groovy Console 7.0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ aem-groovy-console ---
[INFO] Deleting /Users/cmrockwe/Documents/a3workspace/cq-groovy-console/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ aem-groovy-console ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ aem-groovy-console ---
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO] 
[INFO] --- maven-scr-plugin:1.20.0:scr (generate-scr-scrdescriptor) @ aem-groovy-console ---
[INFO] Generating 1 MetaType Descriptors in /Users/cmrockwe/Documents/a3workspace/cq-groovy-console/target/classes/OSGI-INF/metatype/com.citytechinc.aem.groovy.console.configuration.impl.DefaultConfigurationService.xml
[INFO] Writing 1 Service Component Descriptors to /Users/cmrockwe/Documents/a3workspace/cq-groovy-console/target/classes/OSGI-INF/com.citytechinc.aem.groovy.console.audit.impl.DefaultAuditService.xml
[INFO] Writing 1 Service Component Descriptors to /Users/cmrockwe/Documents/a3workspace/cq-groovy-console/target/classes/OSGI-INF/com.citytechinc.aem.groovy.console.configuration.impl.DefaultConfigurationService.xml
[INFO] Writing 1 Service Component Descriptors to /Users/cmrockwe/Documents/a3workspace/cq-groovy-console/target/classes/OSGI-INF/com.citytechinc.aem.groovy.console.extension.impl.DefaultBindingExtensionProvider.xml
[INFO] Writing 1 Service Component Descriptors to /Users/cmrockwe/Documents/a3workspace/cq-groovy-console/target/classes/OSGI-INF/com.citytechinc.aem.groovy.console.extension.impl.DefaultExtensionService.xml
[INFO] Writing 1 Service Component Descriptors to /Users/cmrockwe/Documents/a3workspace/cq-groovy-console/target/classes/OSGI-INF/com.citytechinc.aem.groovy.console.extension.impl.DefaultScriptMetaClassExtensionProvider.xml
[INFO] Writing 1 Service Component Descriptors to /Users/cmrockwe/Documents/a3workspace/cq-groovy-console/target/classes/OSGI-INF/com.citytechinc.aem.groovy.console.extension.impl.DefaultStarImportExtensionProvider.xml
[INFO] Writing 1 Service Component Descriptors to /Users/cmrockwe/Documents/a3workspace/cq-groovy-console/target/classes/OSGI-INF/com.citytechinc.aem.groovy.console.impl.DefaultGroovyConsoleService.xml
[INFO] Writing 1 Service Component Descriptors to /Users/cmrockwe/Documents/a3workspace/cq-groovy-console/target/classes/OSGI-INF/com.citytechinc.aem.groovy.console.notification.impl.EmailNotificationService.xml
[INFO] Writing 1 Service Component Descriptors to /Users/cmrockwe/Documents/a3workspace/cq-groovy-console/target/classes/OSGI-INF/com.citytechinc.aem.groovy.console.servlets.AuditServlet.xml
[INFO] Writing 1 Service Component Descriptors to /Users/cmrockwe/Documents/a3workspace/cq-groovy-console/target/classes/OSGI-INF/com.citytechinc.aem.groovy.console.servlets.ScriptPostServlet.xml
[INFO] Writing 1 Service Component Descriptors to /Users/cmrockwe/Documents/a3workspace/cq-groovy-console/target/classes/OSGI-INF/com.citytechinc.aem.groovy.console.servlets.ScriptSavingServlet.xml
[INFO] Writing 1 Service Component Descriptors to /Users/cmrockwe/Documents/a3workspace/cq-groovy-console/target/classes/OSGI-INF/com.citytechinc.aem.groovy.console.servlets.ServicesListServlet.xml
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ aem-groovy-console ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ aem-groovy-console ---
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ aem-groovy-console ---
[INFO] Surefire report directory: /Users/cmrockwe/Documents/a3workspace/cq-groovy-console/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.citytechinc.aem.groovy.console.audit.impl.DefaultAuditServiceSpec
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.418 sec <<< FAILURE! - in com.citytechinc.aem.groovy.console.audit.impl.DefaultAuditServiceSpec
com.citytechinc.aem.groovy.console.audit.impl.DefaultAuditServiceSpec  Time elapsed: 1.41 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/commons/pool/impl/GenericObjectPool
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.getDriverDataSource(ConnectionFactory.java:312)
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.createDataSource(ConnectionFactory.java:240)
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.getDataSource(ConnectionFactory.java:166)
	at org.apache.jackrabbit.core.persistence.pool.BundleDbPersistenceManager.getDataSource(BundleDbPersistenceManager.java:566)
	at org.apache.jackrabbit.core.persistence.pool.BundleDbPersistenceManager.init(BundleDbPersistenceManager.java:534)
	at org.apache.jackrabbit.core.persistence.pool.DerbyPersistenceManager.init(DerbyPersistenceManager.java:250)
	at org.apache.jackrabbit.core.RepositoryImpl.createPersistenceManager(RepositoryImpl.java:1353)
	at org.apache.jackrabbit.core.RepositoryImpl.createVersionManager(RepositoryImpl.java:503)
	at org.apache.jackrabbit.core.RepositoryImpl.<init>(RepositoryImpl.java:329)
	at org.apache.jackrabbit.core.RepositoryImpl.create(RepositoryImpl.java:605)
	at org.apache.jackrabbit.core.TransientRepository$3.getRepository(TransientRepository.java:250)
	at org.apache.jackrabbit.core.TransientRepository.startRepository(TransientRepository.java:280)
	at org.apache.jackrabbit.core.TransientRepository.login(TransientRepository.java:376)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil$RepositoryWrapper.login(RepositoryUtil.java:189)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil$RepositoryWrapper.loginAdministrative(RepositoryUtil.java:210)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil.startRepository(RepositoryUtil.java:108)
	at com.citytechinc.aem.prosper.specs.ProsperSpec.getRepository(ProsperSpec.groovy:380)
	at com.citytechinc.aem.prosper.specs.ProsperSpec.setupSpec(ProsperSpec.groovy:79)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.pool.impl.GenericObjectPool
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.getDriverDataSource(ConnectionFactory.java:312)
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.createDataSource(ConnectionFactory.java:240)
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.getDataSource(ConnectionFactory.java:166)
	at org.apache.jackrabbit.core.persistence.pool.BundleDbPersistenceManager.getDataSource(BundleDbPersistenceManager.java:566)
	at org.apache.jackrabbit.core.persistence.pool.BundleDbPersistenceManager.init(BundleDbPersistenceManager.java:534)
	at org.apache.jackrabbit.core.persistence.pool.DerbyPersistenceManager.init(DerbyPersistenceManager.java:250)
	at org.apache.jackrabbit.core.RepositoryImpl.createPersistenceManager(RepositoryImpl.java:1353)
	at org.apache.jackrabbit.core.RepositoryImpl.createVersionManager(RepositoryImpl.java:503)
	at org.apache.jackrabbit.core.RepositoryImpl.<init>(RepositoryImpl.java:329)
	at org.apache.jackrabbit.core.RepositoryImpl.create(RepositoryImpl.java:605)
	at org.apache.jackrabbit.core.TransientRepository$3.getRepository(TransientRepository.java:250)
	at org.apache.jackrabbit.core.TransientRepository.startRepository(TransientRepository.java:280)
	at org.apache.jackrabbit.core.TransientRepository.login(TransientRepository.java:376)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil$RepositoryWrapper.login(RepositoryUtil.java:189)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil$RepositoryWrapper.loginAdministrative(RepositoryUtil.java:210)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil.startRepository(RepositoryUtil.java:108)
	at com.citytechinc.aem.prosper.specs.ProsperSpec.getRepository(ProsperSpec.groovy:380)
	at com.citytechinc.aem.prosper.specs.ProsperSpec.setupSpec(ProsperSpec.groovy:79)

com.citytechinc.aem.groovy.console.audit.impl.DefaultAuditServiceSpec  Time elapsed: 1.418 sec  <<< ERROR!
java.lang.NullPointerException: Cannot get property 'rootNode' on null object
	at com.citytechinc.aem.prosper.specs.ProsperSpec.removeAllNodes(ProsperSpec.groovy:111)
	at com.citytechinc.aem.prosper.specs.ProsperSpec.cleanupSpec(ProsperSpec.groovy:94)

Running com.citytechinc.aem.groovy.console.services.impl.DefaultExtensionServiceSpec
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.064 sec <<< FAILURE! - in com.citytechinc.aem.groovy.console.services.impl.DefaultExtensionServiceSpec
com.citytechinc.aem.groovy.console.services.impl.DefaultExtensionServiceSpec  Time elapsed: 0.063 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/commons/pool/impl/GenericObjectPool
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.getDriverDataSource(ConnectionFactory.java:312)
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.createDataSource(ConnectionFactory.java:240)
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.getDataSource(ConnectionFactory.java:166)
	at org.apache.jackrabbit.core.persistence.pool.BundleDbPersistenceManager.getDataSource(BundleDbPersistenceManager.java:566)
	at org.apache.jackrabbit.core.persistence.pool.BundleDbPersistenceManager.init(BundleDbPersistenceManager.java:534)
	at org.apache.jackrabbit.core.persistence.pool.DerbyPersistenceManager.init(DerbyPersistenceManager.java:250)
	at org.apache.jackrabbit.core.RepositoryImpl.createPersistenceManager(RepositoryImpl.java:1353)
	at org.apache.jackrabbit.core.RepositoryImpl.createVersionManager(RepositoryImpl.java:503)
	at org.apache.jackrabbit.core.RepositoryImpl.<init>(RepositoryImpl.java:329)
	at org.apache.jackrabbit.core.RepositoryImpl.create(RepositoryImpl.java:605)
	at org.apache.jackrabbit.core.TransientRepository$3.getRepository(TransientRepository.java:250)
	at org.apache.jackrabbit.core.TransientRepository.startRepository(TransientRepository.java:280)
	at org.apache.jackrabbit.core.TransientRepository.login(TransientRepository.java:376)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil$RepositoryWrapper.login(RepositoryUtil.java:189)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil$RepositoryWrapper.loginAdministrative(RepositoryUtil.java:210)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil.startRepository(RepositoryUtil.java:108)
	at com.citytechinc.aem.prosper.specs.ProsperSpec.getRepository(ProsperSpec.groovy:380)
	at com.citytechinc.aem.prosper.specs.ProsperSpec.setupSpec(ProsperSpec.groovy:79)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.pool.impl.GenericObjectPool
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.getDriverDataSource(ConnectionFactory.java:312)
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.createDataSource(ConnectionFactory.java:240)
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.getDataSource(ConnectionFactory.java:166)
	at org.apache.jackrabbit.core.persistence.pool.BundleDbPersistenceManager.getDataSource(BundleDbPersistenceManager.java:566)
	at org.apache.jackrabbit.core.persistence.pool.BundleDbPersistenceManager.init(BundleDbPersistenceManager.java:534)
	at org.apache.jackrabbit.core.persistence.pool.DerbyPersistenceManager.init(DerbyPersistenceManager.java:250)
	at org.apache.jackrabbit.core.RepositoryImpl.createPersistenceManager(RepositoryImpl.java:1353)
	at org.apache.jackrabbit.core.RepositoryImpl.createVersionManager(RepositoryImpl.java:503)
	at org.apache.jackrabbit.core.RepositoryImpl.<init>(RepositoryImpl.java:329)
	at org.apache.jackrabbit.core.RepositoryImpl.create(RepositoryImpl.java:605)
	at org.apache.jackrabbit.core.TransientRepository$3.getRepository(TransientRepository.java:250)
	at org.apache.jackrabbit.core.TransientRepository.startRepository(TransientRepository.java:280)
	at org.apache.jackrabbit.core.TransientRepository.login(TransientRepository.java:376)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil$RepositoryWrapper.login(RepositoryUtil.java:189)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil$RepositoryWrapper.loginAdministrative(RepositoryUtil.java:210)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil.startRepository(RepositoryUtil.java:108)
	at com.citytechinc.aem.prosper.specs.ProsperSpec.getRepository(ProsperSpec.groovy:380)
	at com.citytechinc.aem.prosper.specs.ProsperSpec.setupSpec(ProsperSpec.groovy:79)

com.citytechinc.aem.groovy.console.services.impl.DefaultExtensionServiceSpec  Time elapsed: 0.064 sec  <<< ERROR!
java.lang.NullPointerException: Cannot get property 'rootNode' on null object
	at com.citytechinc.aem.prosper.specs.ProsperSpec.removeAllNodes(ProsperSpec.groovy:111)
	at com.citytechinc.aem.prosper.specs.ProsperSpec.cleanupSpec(ProsperSpec.groovy:94)

Running com.citytechinc.aem.groovy.console.services.impl.DefaultGroovyConsoleServiceSpec
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.083 sec <<< FAILURE! - in com.citytechinc.aem.groovy.console.services.impl.DefaultGroovyConsoleServiceSpec
com.citytechinc.aem.groovy.console.services.impl.DefaultGroovyConsoleServiceSpec  Time elapsed: 0.083 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/commons/pool/impl/GenericObjectPool
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.getDriverDataSource(ConnectionFactory.java:312)
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.createDataSource(ConnectionFactory.java:240)
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.getDataSource(ConnectionFactory.java:166)
	at org.apache.jackrabbit.core.persistence.pool.BundleDbPersistenceManager.getDataSource(BundleDbPersistenceManager.java:566)
	at org.apache.jackrabbit.core.persistence.pool.BundleDbPersistenceManager.init(BundleDbPersistenceManager.java:534)
	at org.apache.jackrabbit.core.persistence.pool.DerbyPersistenceManager.init(DerbyPersistenceManager.java:250)
	at org.apache.jackrabbit.core.RepositoryImpl.createPersistenceManager(RepositoryImpl.java:1353)
	at org.apache.jackrabbit.core.RepositoryImpl.createVersionManager(RepositoryImpl.java:503)
	at org.apache.jackrabbit.core.RepositoryImpl.<init>(RepositoryImpl.java:329)
	at org.apache.jackrabbit.core.RepositoryImpl.create(RepositoryImpl.java:605)
	at org.apache.jackrabbit.core.TransientRepository$3.getRepository(TransientRepository.java:250)
	at org.apache.jackrabbit.core.TransientRepository.startRepository(TransientRepository.java:280)
	at org.apache.jackrabbit.core.TransientRepository.login(TransientRepository.java:376)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil$RepositoryWrapper.login(RepositoryUtil.java:189)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil$RepositoryWrapper.loginAdministrative(RepositoryUtil.java:210)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil.startRepository(RepositoryUtil.java:108)
	at com.citytechinc.aem.prosper.specs.ProsperSpec.getRepository(ProsperSpec.groovy:380)
	at com.citytechinc.aem.prosper.specs.ProsperSpec.setupSpec(ProsperSpec.groovy:79)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.pool.impl.GenericObjectPool
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.getDriverDataSource(ConnectionFactory.java:312)
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.createDataSource(ConnectionFactory.java:240)
	at org.apache.jackrabbit.core.util.db.ConnectionFactory.getDataSource(ConnectionFactory.java:166)
	at org.apache.jackrabbit.core.persistence.pool.BundleDbPersistenceManager.getDataSource(BundleDbPersistenceManager.java:566)
	at org.apache.jackrabbit.core.persistence.pool.BundleDbPersistenceManager.init(BundleDbPersistenceManager.java:534)
	at org.apache.jackrabbit.core.persistence.pool.DerbyPersistenceManager.init(DerbyPersistenceManager.java:250)
	at org.apache.jackrabbit.core.RepositoryImpl.createPersistenceManager(RepositoryImpl.java:1353)
	at org.apache.jackrabbit.core.RepositoryImpl.createVersionManager(RepositoryImpl.java:503)
	at org.apache.jackrabbit.core.RepositoryImpl.<init>(RepositoryImpl.java:329)
	at org.apache.jackrabbit.core.RepositoryImpl.create(RepositoryImpl.java:605)
	at org.apache.jackrabbit.core.TransientRepository$3.getRepository(TransientRepository.java:250)
	at org.apache.jackrabbit.core.TransientRepository.startRepository(TransientRepository.java:280)
	at org.apache.jackrabbit.core.TransientRepository.login(TransientRepository.java:376)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil$RepositoryWrapper.login(RepositoryUtil.java:189)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil$RepositoryWrapper.loginAdministrative(RepositoryUtil.java:210)
	at org.apache.sling.commons.testing.jcr.RepositoryUtil.startRepository(RepositoryUtil.java:108)
	at com.citytechinc.aem.prosper.specs.ProsperSpec.getRepository(ProsperSpec.groovy:380)
	at com.citytechinc.aem.prosper.specs.ProsperSpec.setupSpec(ProsperSpec.groovy:79)

com.citytechinc.aem.groovy.console.services.impl.DefaultGroovyConsoleServiceSpec  Time elapsed: 0.083 sec  <<< ERROR!
java.lang.NullPointerException: Cannot get property 'rootNode' on null object
	at com.citytechinc.aem.prosper.specs.ProsperSpec.removeAllNodes(ProsperSpec.groovy:111)
	at com.citytechinc.aem.prosper.specs.ProsperSpec.cleanupSpec(ProsperSpec.groovy:94)


Results :

Tests in error: 
  DefaultAuditServiceSpec>ProsperSpec.setupSpec:79->ProsperSpec.getRepository:380 » NoClassDefFound
  DefaultAuditServiceSpec>ProsperSpec.cleanupSpec:94->ProsperSpec.removeAllNodes:111 » NullPointer
  DefaultExtensionServiceSpec>ProsperSpec.setupSpec:79->ProsperSpec.getRepository:380 » NoClassDefFound
  DefaultExtensionServiceSpec>ProsperSpec.cleanupSpec:94->ProsperSpec.removeAllNodes:111 » NullPointer
  DefaultGroovyConsoleServiceSpec>ProsperSpec.setupSpec:79->ProsperSpec.getRepository:380 » NoClassDefFound
  DefaultGroovyConsoleServiceSpec>ProsperSpec.cleanupSpec:94->ProsperSpec.removeAllNodes:111 » NullPointer

Tests run: 6, Failures: 0, Errors: 6, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.187s
[INFO] Finished at: Mon May 11 14:38:56 EDT 2015
[INFO] Final Memory: 25M/449M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project aem-groovy-console: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/cmrockwe/Documents/a3workspace/cq-groovy-console/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
ldev-x-cmrockwe:cq-groovy-console cmrockwe$

**Comment by steeleforge** [comment]
Can you try to to force an update mvncentral update with the -U flag to your mvn command?

In your local maven repo, do you see this folder structure? .m2\repository\commons-pool ?

Looks like a missing transitive dep, specifically commons-pool, based on the below: java.lang.NoClassDefFoundError: org/apache/commons/pool/impl/GenericObjectPool

**Comment by cmrockwell** [comment]
I don't have ~/.m2/repository/commons-pool in my local m2 repo. I tried mvn clean install -U, but no joy.

**Comment by steeleforge** [comment]
Hi @cmrockwell  -- sorry I didn't have any other suggestions. Did you find a resolution for this one?

**Comment by lykorian** [comment]
commons-pool is indeed a transitive dependency of org.apache.sling.commons.testing, but I wonder why the tests would fail on different platforms.  Unless there's some type of environment-based profile being triggered during the transient repository initialization.

@cmrockwell, if you're still experiencing this issue, can you try adding the following dependency to the pom?

```
<dependency>
    <groupId>commons-pool</groupId>
    <artifactId>commons-pool</artifactId>
    <version>1.3</version>
    <scope>test</scope>
</dependency>
```

**Comment by cmrockwell** [comment]
Yes, that fixed it. Thank you!
