### ISSUE TITLE
Groovy Console 8.0.0 Stopped Working on AEM 6.1

### ISSUE THREAD

**Issue by david-hosier** [Citytechinc/cq-groovy-console#42]
I had installed the console in my local AEM 6.1 setup as one of the first things I did when moving to AEM 6.1. It was working initially and has since stopped working. I uninstalled the package in the package manager and manually deleted the stuff under /apps/groovyconsole and /etc/groovyconsole. Then I restarted my server and attempted package installation from scratch. When I try to install, I get the messages below in the server log. I'm not sure what's happening here or why it once worked and no longer does. I'm wondering if there is something about my application's packages that is causing an issue, but I've never seen an error like this, so I'm just not sure.

```
05.11.2015 22:52:30.266 *INFO* [qtp1897326799-57] org.apache.jackrabbit.vault.packaging.impl.JcrPackageDefinitionImpl unwrapping package :aem-groovy-console:8.0.0
05.11.2015 22:52:30.582 *INFO* [qtp1897326799-56] org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl Creating snapshot for .snapshot:aem-groovy-console:8.0.0.
05.11.2015 22:52:30.695 *WARN* [qtp1897326799-56] org.apache.jackrabbit.oak.jcr.session.ItemImpl Item#refresh invokes Session#refresh!
05.11.2015 22:52:30.699 *INFO* [qtp1897326799-56] org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl Creating snapshot for .snapshot:aem-groovy-console:8.0.0 completed.
05.11.2015 22:52:30.700 *INFO* [qtp1897326799-56] org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage Extracting :aem-groovy-console:8.0.0
05.11.2015 22:52:30.935 *INFO* [qtp1897326799-56] org.apache.jackrabbit.vault.fs.io.AutoSave Threshold of 1024 reached. saving approx 301 transient changes. 0 unresolved
05.11.2015 22:52:31.751 *INFO* [qtp1897326799-56] org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage Extracting :aem-groovy-console:8.0.0 completed.
05.11.2015 22:52:31.777 *INFO* [pool-6-thread-10] com.day.cq.wcm.core.impl.components.ComponentCacheImpl Detecting component change. invalidating cache.
05.11.2015 22:52:31.796 *INFO* [pool-6-thread-15] com.adobe.granite.ui.clientlibs.impl.CompilerProviderImpl no compiler found for txt
05.11.2015 22:52:31.797 *WARN* [pool-6-thread-15] com.adobe.granite.ui.clientlibs.impl.FileBundle Referenced path in /etc/groovyconsole/clientlibs/js.txt does not exist: /etc/groovyconsole/clientlibs/js/theme-kr_theme.js
05.11.2015 22:52:31.797 *INFO* [pool-6-thread-15] com.adobe.granite.ui.clientlibs.impl.CompilerProviderImpl no compiler found for txt
05.11.2015 22:52:31.798 *INFO* [pool-6-thread-15] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl detected [JS, CSS] library: /etc/groovyconsole/clientlibs, sourced from 55 files.
05.11.2015 22:52:31.806 *INFO* [pool-6-thread-15] com.adobe.granite.ui.clientlibs.impl.LibraryCacheImpl Rebuilt 1455 ancestor paths
05.11.2015 22:52:32.368 *INFO* [JcrInstaller.1] org.apache.sling.installer.provider.jcr.impl.WatchedFolder Watching folder /apps/groovyconsole/install (priority 200)
05.11.2015 22:52:32.887 *INFO* [JcrInstaller.1] org.apache.sling.installer.provider.jcr.impl.JcrInstaller Registering resource with OSGi installer: [InstallableResource, priority=200, id=/apps/groovyconsole/install/aem-groovy-extension-bundle-1.0.1.jar, InstallableResource, priority=200, id=/apps/groovyconsole/install/aem-groovy-console-8.0.0.jar, InstallableResource, priority=200, id=/apps/groovyconsole/install/groovy-all-2.4.3.jar]
05.11.2015 22:52:33.092 *INFO* [OsgiInstallerImpl] org.apache.sling.installer.core.impl.tasks.BundleInstallTask Exception during install of bundle TaskResource(url=jcrinstall:/apps/groovyconsole/install/aem-groovy-console-8.0.0.jar, entity=bundle:aem-groovy-console, state=INSTALL, attributes=[org.apache.sling.installer.api.tasks.ResourceTransformer=:24:43:21:, Bundle-SymbolicName=aem-groovy-console, Bundle-Version=8.0.0], digest=1446792750855) : Bundle installation rejected by hook.. Retrying later.
org.osgi.framework.BundleException: Bundle installation rejected by hook.
	at org.apache.felix.framework.Felix.installBundle(Felix.java:3123)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:167)
	at org.apache.sling.installer.core.impl.tasks.BundleInstallTask.execute(BundleInstallTask.java:47)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:847)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:689)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:265)
	at java.lang.Thread.run(Thread.java:722)
05.11.2015 22:52:33.092 *INFO* [OsgiInstallerImpl] org.apache.sling.installer.core.impl.tasks.BundleInstallTask Exception during install of bundle TaskResource(url=jcrinstall:/apps/groovyconsole/install/aem-groovy-extension-bundle-1.0.1.jar, entity=bundle:aem-groovy-extension-bundle, state=INSTALL, attributes=[org.apache.sling.installer.api.tasks.ResourceTransformer=:24:43:21:, Bundle-SymbolicName=aem-groovy-extension-bundle, Bundle-Version=1.0.1], digest=1446792750853) : Bundle installation rejected by hook.. Retrying later.
org.osgi.framework.BundleException: Bundle installation rejected by hook.
	at org.apache.felix.framework.Felix.installBundle(Felix.java:3123)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:167)
	at org.apache.sling.installer.core.impl.tasks.BundleInstallTask.execute(BundleInstallTask.java:47)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:847)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:689)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:265)
	at java.lang.Thread.run(Thread.java:722)
05.11.2015 22:52:33.092 *INFO* [OsgiInstallerImpl] org.apache.sling.installer.core.impl.tasks.BundleInstallTask Exception during install of bundle TaskResource(url=jcrinstall:/apps/groovyconsole/install/groovy-all-2.4.3.jar, entity=bundle:groovy-all, state=INSTALL, attributes=[org.apache.sling.installer.api.tasks.ResourceTransformer=:24:43:21:, Bundle-SymbolicName=groovy-all, Bundle-Version=2.4.3], digest=1446792750852) : Bundle installation rejected by hook.. Retrying later.
org.osgi.framework.BundleException: Bundle installation rejected by hook.
	at org.apache.felix.framework.Felix.installBundle(Felix.java:3123)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:167)
	at org.apache.sling.installer.core.impl.tasks.BundleInstallTask.execute(BundleInstallTask.java:47)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:847)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:689)
	at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:265)
	at java.lang.Thread.run(Thread.java:722)
```

**Comment by lykorian** [comment]
@david-hosier, did this issue ever resolve for you?  Have you tried the latest snapshot?  This looks like the type of OSGi error that we would see intermittently, but was often resolved by restarting and/or uninstalling/reinstalling the bundle(s) in question.
